### ISSUE TITLE
Add randomness

### ISSUE THREAD

**Issue by m-ender** [m-ender/retina#50]
I'm not entirely sure yet how to implement this, but probably via a new stage type that can perform one of several random tasks, depending on configuration. Several potentially useful ways to introduce randomness are:
- Shuffle each match.
- Shuffle all matches while leaving each match intact. (e.g. matching `\d+` on `ab12cd34ef56gh` might yield `ab56cd12ef34gh`)
- Return one of the matches at random.
- Use one of several regexes (or stages) at random.
- Apply one of several substitutions at random.
- Insert one or more random characters.
- etc...

**Comment by barbuz** [comment]
Wouldn't it be enough to add an option to the sort stage in order to make it shuffle the matches instead of sorting them? (it would of course be incompatible with the current `$`,`^`,`#` options)

**Comment by m-ender** [comment]
@barbuz That's just one way of randomisation. It would be possible to build all the others on top of it but that's not necessarily very convenient. It might be good to have random versions of other stage types as well, e.g. having `M` return a random match so you can pick a random element from a list (instead of shuffling the list and then picking the first element).

**Comment by barbuz** [comment]
I was just suggesting what seems the easiest way to introduce randomness. Having just one source of randomness would make Retina usable for a number of tasks which at the moment can't be performed; adding other sources of randomness to optimize convenience/length in different situations can always be done later, but it's not as needed as adding the first one.

**Comment by m-ender** [comment]
Yes, I realise that this is something that needs to be added quite urgently, and it will be part of the next release (with as many other ways of randomisation as I can be bothered to implement at the time), but I can't yet tell how soon that is going to happen.

**Comment by m-ender** [comment]
Various forms of randomness have been added to Retina 1.0. There's a `@` flag which is available everywhere and chooses only one of all the matches at random (after applying the match limit). This makes it possible to model most kinds of useful random behaviours (return a random match, replace a random match, apply a substage only to a random match etc.

There's also a `&` flag which some stages recognise for additional random behaviour more relevant to their usual function. Sort shuffles the matches, Reverse shuffles each match, Grep returns a random line, AntiGrep discards a random line, Deduplicate keeps a random copy of each set of strings, Split returns a random element from the final split list, `%` processes a random line, and groups run one of the substages at random (instead of all of them sequentially). I might add a few more here if I come up with good ideas.
