### ISSUE TITLE
New stage type: padding

### ISSUE THREAD

**Issue by m-ender** [m-ender/retina#59]
The idea would be to pad all matches to the length of the longest with a configurable character (space by default). There should be an option to pad on the left instead of the right. The most common use case would probably be to pad out ragged input to a rectangle, so `.+` would be a sensible default regex.

Not sure yet about a) padding N characters more than the longest match or b) padding to exactly N characters.

**Comment by ConorOBrien-Foxx** [comment]
A wild thought, perhaps you could have a regex that describes the padding character. Like, `0{0,5}` would add up to 5 zeroes at the end of line. I'm not sure about the specifics however.

**Comment by m-ender** [comment]
Generating strings from regex is kinda weird (and would probably require writing my own regex engine, which I don't have yet). Like, what do you pad with if the given regex is `[ab]{0,5}`? I think for now I'll just stick with specifying a character and a width, but I'll keep it in mind.

**Comment by m-ender** [comment]
This has been implemented for Retina 1.0. The padding width is taken from the maximum width of match *replacements* which lets you do both "pad to N" and "pad to N more than the longest match" (and various other things). It's possible to specify either a character for padding or a string which gets repeatedly cyclically. Both left- and right-padding are possible. The stage character is currently `P`.
