### ISSUE TITLE
Custom split delimiter

### ISSUE THREAD

**Issue by CatsAreFluffy** [m-ender/retina#62]
A third input for the Split stage could be a delimiter to use instead of `\n`.

**Comment by m-ender** [comment]
Changing delimiters will be part of #8 (which is also relevant to Match stages, for example).

**Comment by CatsAreFluffy** [comment]
Though a third input (like in Transliteration) would allow longer delimiters.

**Comment by m-ender** [comment]
I'm not 100% sure yet *how* formatting configuration will work but it will definitely support arbitrary strings.
