### ISSUE TITLE
Short versions of common patterns

### ISSUE THREAD

**Issue by CatsAreFluffy** [m-ender/retina#64]
For example, `.+` could be one of the characters from A0-FF in ISO 8859-1.
Other useful shortenings could include `.*`, character classes (ie `\d`), `(x)` (x is a single char), stage headers (ie <code>M&#96;</code>), stage headers with common configuration (ie <code>M!&#96;</code>)...

**Comment by m-ender** [comment]
Sorry, but I'm not planning to add more non-ASCII characters to Retina. I'm already not super happy with having `¶` in the language. Retina isn't super competitive as a golfing language to begin with, and no amount of non-ASCII shorthand is going to fix that. I'll keep Retina terse, but usable.
