### ISSUE TITLE
Match mode option: give access to capturing information

### ISSUE THREAD

**Issue by m-ender** [m-ender/retina#7]
This is a rather complicated task, because .NET's capturing is very flexible. There are named and unnamed groups, and each group can capture an entire stack of strings.

Ideally giving access to the capturing system should be flexible enough to return number of captures, _if_ something was captured, the actual contents of all captures, or just the last capture of one or more groups. This might need some fundamental rethinking of the configuration system.

**Comment by mbuettner** [comment]
This feature should probably be designed in conjunction with issue #8.

**Comment by m-ender** [comment]
This isn't really necessary any more. In Retina 1.0 you can attach a replacement to a List stage (what used to be Match with `!`), and you can extract a bunch of capturing information in substitutions. I might add some more features to substitution syntax to make this even more flexible, but I don't think this needs a separate stage at this point.
