### ISSUE TITLE
Updating Documentation?

### ISSUE THREAD

**Issue by pokeball99** [m-ender/retina#70]
it seems that Documentation for Retina has not been updated in about 11 months, unless i'm simply overlooking something

**Comment by m-ender** [comment]
That's right, but the documentation should be up to date for Retina 0.8.2 which is still [the latest official release](https://github.com/m-ender/retina/releases). I'm currently working on a massive Retina 1.0 release and while I do everything is still a bit in flux. That said, I should hopefully get done with the coding today or tomorrow and then I'll get to work on writing completely new docs.

**Comment by m-ender** [comment]
There you go. Retina 1.0.0 is done and the docs are updated. They're also incredibly meaty now though. I'll try to work on a more digestible tutorial some time soon.
