### ISSUE TITLE
Control formatting through configuration

### ISSUE THREAD

**Issue by m-ender** [m-ender/retina#8]
This spans a lot of different modes and other options - whenever a mode is capable of returning a list, it would be convenient to be able to specify custom delimiters, as opposed to the simple newline separation.

**Comment by mbuettner** [comment]
This feature should probably be designed in conjunction with issue #7.

**Comment by m-ender** [comment]
This has been added for Retina 1.0. `[`, `|` and `]` are options which are followed by a character or string and determine the list start, delimiter and end, respectively.
